### ISSUE TITLE
部署成功，页面404

### ISSUE THREAD

**Issue by DemoorBug** [Cptmacmillan2022007/IX-RXVT#2]
因为以前的账号封了，创建了一个新账号来部署此项目，项目部署成功，页面也是404，但是按照以前的设置也不能访问外网

**Comment by DemoorBug** [comment]
v2ray的设置也是根据你页面来的
https://psras.herokuapp.com/

**Comment by Cptmacmillan2022007** [comment]
workers反代被ban了，自行寻找其他方法

**Comment by DemoorBug** [comment]
> 

我知道被ban了，早已经改自己的域名了
